theme: jekyll-theme-cayman
title: Axion Astrophysical Fluxes
description: A repository with data, fits and codes for axion astrophysical fluxes.
url: "https://ggrillidc.github.io/AxionAstrophysicalFluxes"

# Set this to true to get LaTeX math equation support
use_math: true

# MathJax support
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# Add MathJax to the head of every page
include:
  - head.html

# Set this to true to display the summary of your blog post under your title on the Home page.
show_description: true